---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: amazing-rainbow-1625305651
  region: us-east-1

# other cluster config ...

gitops:
  flux:
    gitProvider: github      # required. options are github, gitlab or git
    flags:                   # required. arbitrary map[string]string for all flux args.
    # these args are not controlled by eksctl. see https://fluxcd.io/docs/get-started/ for all available flags
      owner: "bill-canda"
      repository: "dalek"
      private: "false"
      branch: "master"
      namespace: "flux-system"
      path: "clusters/amazing-rainbow-1625305651"
